//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Match_IPL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchId { get; set; }
        public Nullable<int> TeamOneId { get; set; }
        public Nullable<int> TeamTwoId { get; set; }
        public Nullable<int> VenueId { get; set; }
        public Nullable<int> PhotoGroupId { get; set; }
    }
}
