<%@ Page Title="" Language="C#" MasterPageFile="~/Employee_Master.Master" AutoEventWireup="true" CodeBehind="Venue.aspx.cs" Inherits="Presentation_Layer.Account.Employee.Emp_Venue.Venue" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <br />
    <br />
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
    </p>

   
        <center>
   <div style="height:100%;" class="panel panel-default" >
       <div class="panel panel-info">
       <div class="panel-heading"> <h3>Venue Info</h3></div></div>
   
    
       <div class="panel-body" >
       
           <div>
              
               <asp:Label Text="Search:" style="text-align:right" runat="server"></asp:Label>
               <asp:TextBox style="text-align:left" OnTextChanged="searchtxt1_TextChanged" runat="server" ID="searchtxt1" AutoPostBack="true" ></asp:TextBox><i class="fa fa-search"></i>
                 <button style="text-align:left" onclick="btnrefresh" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span> Refresh</button>
           </div>
           <br /><br />
           <div style="width: 50%; height: 290px;" >
            
  <asp:Panel runat="server" ID="panel1">
      <a href="~/Account/Employee/Emp_Venue/Add_Venue" runat="server">Add Venue</a>
  <asp:GridView ID="GridView1" runat="server"  CssClass= "table table-striped table-bordered table-condensed" AllowPaging="True" DataKeyNames="VenueName" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1">

      <Columns>
          <asp:BoundField DataField="Location" HeaderText="Location" SortExpression="Location" />
          <asp:BoundField DataField="VenueDescription" HeaderText="VenueDescription" SortExpression="VenueDescription" />
          <asp:BoundField DataField="VenueName" HeaderText="VenueName" SortExpression="VenueName" />
      </Columns>

  </asp:GridView>
      <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" DeleteCommand="DELETE FROM IPL_MGMT_SYSTEM.Venue WHERE (VenueName = @VenueName)" UpdateCommand="update IPL_MGMT_SYSTEM.Venue set [VenueName]=@VenueName, [Location]=@Location, [VenueDescription]=@VenueDescription where [VenueName]=@VenueName" SelectCommand="SELECT Location, VenueDescription, VenueName FROM IPL_MGMT_SYSTEM.Venue">
          <DeleteParameters>
              <asp:Parameter Name="VenueName" />
          </DeleteParameters>
      </asp:SqlDataSource>
      </asp:Panel>
               <asp:Panel runat="server" ID="panel2">
                  <asp:GridView ID="GridView2"  CssClass= "table table-striped table-bordered table-condensed" runat="server" AllowPaging="True" DataKeyNames="VenueName" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource2">
                      <Columns>
                          <asp:BoundField DataField="VenueName" HeaderText="Venue Name" SortExpression="VenueName" />
                          <asp:BoundField DataField="Location" HeaderText="Location" SortExpression="Location" />
                          <asp:BoundField DataField="VenueDescription" HeaderText="Venue Description" SortExpression="VenueDescription" />
                      </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" DeleteCommand="delete from IPL_MGMT_SYSTEM.Venue where [VenueName]=@VenueName" UpdateCommand="update IPL_MGMT_SYSTEM.Venue set [VenueName]=@VenueName, [Location]=@Location, [VenueDescription]=@VenueDescription where [VenueName]=@VenueName" SelectCommand="SELECT VenueName,Location, VenueDescription  FROM IPL_MGMT_SYSTEM.Venue where [VenueName]=@VenueName">
                       <DeleteParameters>
                           <asp:Parameter Name="VenueName" />
                       </DeleteParameters>
                       <SelectParameters>
                           <asp:ControlParameter ControlID="searchtxt1" Name="VenueName" PropertyName="Text" />
                       </SelectParameters>
                       <UpdateParameters>
                           <asp:Parameter Name="VenueName" />
                           <asp:Parameter Name="Location" />
                           <asp:Parameter Name="VenueDescription" />
                       </UpdateParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
           </div>
    </div>
    </div>   

            </center>
</asp:Content>
