//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPL_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> Schedule_VenueId { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string MatchName { get; set; }
        public string VenueName { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
