//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPL_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int StatId { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> Played { get; set; }
        public Nullable<int> Won { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> Tied { get; set; }
        public Nullable<int> NR { get; set; }
        public Nullable<decimal> NetRR { get; set; }
        public Nullable<int> Pts { get; set; }
        public Nullable<int> FromPoints { get; set; }
        public string TeamName { get; set; }
    }
}
