//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPL_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> TicketCategoryId { get; set; }
        public Nullable<int> Price { get; set; }
        public string NumberOfTickets { get; set; }
        public string MatchName { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual TicketCategory TicketCategory { get; set; }
    }
}
