<%@ Page Title="" Language="C#" MasterPageFile="~/Employee_Master.Master" AutoEventWireup="true" CodeBehind="Player_Details.aspx.cs" Inherits="Presentation_Layer.Account.Employee.Emp_Player.Player_Details" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
      <br />
    <br />
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
    </p>

   
        <center>
   <div style="height:100%;" class="panel panel-default" >
       <div class="panel panel-info">
       <div class="panel-heading"> <h3>Player Info</h3></div></div>
   
    
       <div class="panel-body" >
       
           <div>
              
               <asp:Label Text="Search:" style="text-align:right" runat="server"></asp:Label>
               <asp:TextBox style="text-align:left" OnTextChanged="searchtxt1_TextChanged" runat="server" ID="searchtxt1" AutoPostBack="true" ></asp:TextBox><i class="fa fa-search"></i>
                 <button style="text-align:left" onclick="btnrefresh" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span> Refresh</button>
           </div>
           <br /><br />
           <div style="width: 50%; height: 290px;" >
            
  <asp:Panel runat="server" ID="panel1">
    <a href="~/Account/Employee/Emp_Player/Add_Player.aspx" runat="server">Add Player Details</a>
   <asp:GridView ID="GridView1" runat="server"  CssClass= "table table-striped table-bordered table-condensed" AllowPaging="True" AllowSorting="True" DataKeyNames="PlayerName" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1">
       <Columns>
           <asp:BoundField DataField="TeamName" HeaderText="TeamName" SortExpression="TeamName" />
           <asp:BoundField DataField="PlayerName" HeaderText="PlayerName" SortExpression="PlayerName" />
           <asp:BoundField DataField="Age" HeaderText="Age" SortExpression="Age" />
           <asp:BoundField DataField="Role" HeaderText="Role" SortExpression="Role" />
           <asp:BoundField DataField="BattingStyle" HeaderText="BattingStyle" SortExpression="BattingStyle" />
           <asp:BoundField DataField="BowlingStyle" HeaderText="BowlingStyle" SortExpression="BowlingStyle" />
           <asp:BoundField DataField="BirthPlace" HeaderText="BirthPlace" SortExpression="BirthPlace" />
       </Columns>
      </asp:GridView>
      <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" DeleteCommand="delete from IPL_MGMT_SYSTEM.Player where [PlayerName]=@PlayerName" UpdateCommand="update IPL_MGMT_SYSTEM.Player set [PlayerName]=@PlayerName, [TeamName]=@TeamName, [Age]=@Age, [Role]=@Role, [BattingStyle]=@BattingStyle, [BowlingStyle]=@BowlingStyle, [BirthPlace]=@BirthPlace where [PlayerName]=@PlayerName" SelectCommand="SELECT  TeamName,PlayerName, Age, Role, BattingStyle, BowlingStyle, BirthPlace FROM IPL_MGMT_SYSTEM.Player">
          <DeleteParameters>
              <asp:Parameter Name="PlayerName" />
          </DeleteParameters>
      </asp:SqlDataSource>
      </asp:Panel>
               <asp:Panel runat="server" ID="panel2">
                <asp:GridView ID="GridView2" runat="server"  CssClass= "table table-striped table-bordered table-condensed" AutoGenerateColumns="False" DataSourceID="SqlDataSource2" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                    <Columns>
                        <asp:BoundField DataField="TeamName" HeaderText="TeamName" SortExpression="TeamName" />
                        <asp:BoundField DataField="PlayerName" HeaderText="PlayerName" SortExpression="PlayerName" />
                        <asp:BoundField DataField="Age" HeaderText="Age" SortExpression="Age" />
                        <asp:BoundField DataField="Role" HeaderText="Role" SortExpression="Role" />
                        <asp:BoundField DataField="BattingStyle" HeaderText="BattingStyle" SortExpression="BattingStyle" />
                        <asp:BoundField DataField="BowlingStyle" HeaderText="BowlingStyle" SortExpression="BowlingStyle" />
                        <asp:BoundField DataField="BirthPlace" HeaderText="BirthPlace" SortExpression="BirthPlace" />
                    </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" DeleteCommand="delete from IPL_MGMT_SYSTEM.Player where [PlayerName]=@PlayerName" SelectCommand="SELECT TeamName,PlayerName, Age, Role, BattingStyle, BowlingStyle, BirthPlace FROM IPL_MGMT_SYSTEM.Player
where [TeamName]=@TeamName">
                       <DeleteParameters>
                           <asp:Parameter Name="PlayerName" />
                       </DeleteParameters>
                       <SelectParameters>
                           <asp:ControlParameter ControlID="searchtxt1" Name="TeamName" PropertyName="Text" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
           </div>
    </div>
    </div>   

            </center>
</asp:Content>
