<%@ Page Title="" Language="C#" MasterPageFile="~/Employee_Master.Master" AutoEventWireup="true" CodeBehind="NewsDetails.aspx.cs" Inherits="Presentation_Layer.Account.Employee.Emp_News.NewsDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <br />
    <br />
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
    </p>

   
        <center>
   <div style="height:100%;" class="panel panel-default" >
       <div class="panel panel-info">
       <div class="panel-heading"> <h3>News Info</h3></div></div>
   
    
       <div class="panel-body" >
       
           <div>
              
               <asp:Label Text="Search:" style="text-align:right" runat="server"></asp:Label>
               <asp:TextBox style="text-align:left" OnTextChanged="searchtxt1_TextChanged" runat="server" ID="searchtxt1" AutoPostBack="true" ></asp:TextBox><i class="fa fa-search"></i>
                 <button style="text-align:left" onclick="btnrefresh" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span> Refresh</button>
           </div>
           <br /><br />
           <div style="width: 50%; height: 290px;" >
          
  <asp:Panel runat="server" ID="panel1">
    <a href="~/Account/Employee/Emp_News/Add_News" runat="server">Add News</a>
                      
<asp:GridView ID="GridView1" runat="server"  CssClass= "table table-striped table-bordered table-condensed" DataKeyNames="MatchName" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
    <Columns>
        <asp:BoundField DataField="MatchName" HeaderText="MatchName" SortExpression="MatchName" />
        <asp:BoundField DataField="NewsDescription" HeaderText="NewsDescription" SortExpression="NewsDescription" />
    </Columns>
      </asp:GridView>
      <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="SELECT MatchName,NewsDescription  FROM IPL_MGMT_SYSTEM.News"  DeleteCommand="delete from IPL_MGMT_SYSTEM.News where [MatchName]=@MatchName" UpdateCommand="update IPL_MGMT_SYSTEM.News set [MatchName]=@MatchName, [NewsDescription]=@NewsDescription where [MatchName]=@MatchName"> </asp:SqlDataSource>
      </asp:Panel>
               <asp:Panel runat="server" ID="panel2">
               <asp:GridView ID="GridView2"  CssClass= "table table-striped table-bordered table-condensed" runat="server" DataKeyNames="MatchName" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource2">
                   <Columns>
                       <asp:BoundField DataField="MatchName" HeaderText="MatchName" SortExpression="MatchName" />
                       <asp:BoundField DataField="NewsDescription" HeaderText="NewsDescription" SortExpression="NewsDescription" />
                   </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="SELECT MatchName,NewsDescription FROM IPL_MGMT_SYSTEM.News where [MatchName]=@MatchName" DeleteCommand="delete from IPL_MGMT_SYSTEM.News where [MatchName]=@MatchName" UpdateCommand="update IPL_MGMT_SYSTEM.News set [MatchName]=@MatchName, [NewsDescription]=@NewsDescription where [MatchName]=@MatchName">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="searchtxt1" Name="MatchName" PropertyName="Text" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
           </div>
    </div>
    </div>   

            </center>
</asp:Content>
