<%@ Page Title="" Language="C#" MasterPageFile="~/Employee_Master.Master" AutoEventWireup="true" CodeBehind="Team_Details.aspx.cs" Inherits="Presentation_Layer.Account.Employee.Emp_Team.Update_Team" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <br />
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
    </p>

   
        <center>
   <div style="height:100%;" class="panel panel-default" >
       <div class="panel panel-info">
       <div class="panel-heading"> <h3>Team Info</h3></div></div>
   
    
       <div class="panel-body" >
       
           <div>
              
               <asp:Label Text="Search:" style="text-align:right" runat="server"></asp:Label>
               <asp:TextBox style="text-align:left" OnTextChanged="searchtxt1_TextChanged" runat="server" ID="searchtxt1" AutoPostBack="true" ></asp:TextBox><i class="fa fa-search"></i>
                 <button style="text-align:left" onclick="btnrefresh" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span> Refresh</button>
           </div>
           <br /><br />
           <div style="width: 50%; height: 290px;" >
            <a href="~/Account/Employee/Emp_Team/Add_Team.aspx" runat="server">Add New Team</a>
  <asp:Panel runat="server" ID="panel1">
       <asp:GridView ID="GridView2" runat="server"  CssClass= "table table-striped table-bordered table-condensed" DataKeyNames="TeamName" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1">
           <Columns>
               <asp:BoundField DataField="TeamName" HeaderText="Team Name" SortExpression="TeamName" />
               <asp:BoundField DataField="HomeGround" HeaderText="Home Ground" SortExpression="HomeGround" />
               <asp:BoundField DataField="Owners" HeaderText="Owners" SortExpression="Owners" />
           </Columns>
       </asp:GridView>    
   
       <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" DeleteCommand="DELETE FROM IPL_MGMT_SYSTEM.Team WHERE (TeamName = @TeamName)" UpdateCommand="update IPL_MGMT_SYSTEM.Team set [TeamName]=@TeamName, [HomeGround]=@HomeGround, [Owners]=@Owners where  [TeamName]=@TeamName"  SelectCommand="SELECT TeamName, HomeGround, Owners FROM IPL_MGMT_SYSTEM.Team">
           <DeleteParameters>
               <asp:Parameter Name="TeamName" />
           </DeleteParameters>
       </asp:SqlDataSource>
   
      </asp:Panel>
               <asp:Panel runat="server" ID="panel2">
                  <asp:GridView ID="GridView1"  CssClass= "table table-striped table-bordered table-condensed" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource3">

                      <Columns>
                          <asp:BoundField DataField="TeamName" HeaderText="Team Name" SortExpression="TeamName" />
                          <asp:BoundField DataField="HomeGround" HeaderText="Home Ground" SortExpression="HomeGround" />
                          <asp:BoundField DataField="Owners" HeaderText="Owners" SortExpression="Owners" />
                      </Columns>

                  </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" SelectCommand="SELECT TeamName, HomeGround, Owners FROM IPL_MGMT_SYSTEM.Team WHERE (TeamName = @TeamName)">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="searchtxt1" Name="TeamName" PropertyName="Text" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
           </div>
    </div>
    </div>   

            </center>
</asp:Content>
