<%@ Page Title="" Language="C#" MasterPageFile="~/Employee_Master.Master" AutoEventWireup="true" CodeBehind="ScheduleDetails.aspx.cs" Inherits="Presentation_Layer.Account.Employee.Emp_Schedule.ScheduleDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <br />
    <br />
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
    </p>

   
        <center>
   <div style="height:100%;" class="panel panel-default" >
       <div class="panel panel-info">
       <div class="panel-heading"> <h3>Schedule Info</h3></div></div>
   
    
       <div class="panel-body" >
       
           <div>
              
               <asp:Label Text="Search:" style="text-align:right" runat="server"></asp:Label>
               <asp:TextBox style="text-align:left" OnTextChanged="searchtxt1_TextChanged" runat="server" ID="searchtxt1" AutoPostBack="true" ></asp:TextBox><i class="fa fa-search"></i>
                 <button style="text-align:left" onclick="btnrefresh" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span> Refresh</button>
           </div>
           <br />
              <a runat="server" style="color:white" href="~/Account/Employee/Emp_Schedule/Add_Schedule.aspx">Add Schedule</a>
           <br />
           <div style="width: 50%; height: 290px;" >    
  <asp:Panel runat="server" ID="panel1">        
   <asp:GridView ID="GridView1"  CssClass= "table table-striped table-bordered table-condensed" runat="server" AllowPaging="True" DataKeyNames="MatchName" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1">
       <Columns>
           <asp:BoundField DataField="MatchName" HeaderText="MatchName" SortExpression="MatchName" />
           <asp:BoundField DataField="VenueName" HeaderText="VenueName" SortExpression="VenueName" />
           <asp:BoundField DataField="ScheduleDate" HeaderText="ScheduleDate" SortExpression="ScheduleDate" />
           <asp:BoundField DataField="StartTime" HeaderText="StartTime" SortExpression="StartTime" />
           <asp:BoundField DataField="EndTime" HeaderText="EndTime" SortExpression="EndTime" />
       </Columns>
      </asp:GridView>
  
      <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" DeleteCommand="delete  FROM IPL_MGMT_SYSTEM.Schedule where [MatchName]=@MatchName" SelectCommand="SELECT  MatchName, VenueName,ScheduleDate, StartTime, EndTime  FROM IPL_MGMT_SYSTEM.Schedule" UpdateCommand="update IPL_MGMT_SYSTEM.Schedule set [MatchName]=@MatchName, [VenueName]=@VenueName, [ScheduleDate]=@ScheduleDate,[StartTime]=@StartTime,[EndTime]=@EndTime where [MatchName]=@MatchName">
          <DeleteParameters>
              <asp:Parameter Name="MatchName" />
          </DeleteParameters>
          <UpdateParameters>
              <asp:Parameter Name="MatchName" />
              <asp:Parameter Name="VenueName" />
              <asp:Parameter Name="ScheduleDate" />
              <asp:Parameter Name="StartTime" />
              <asp:Parameter Name="EndTime" />
          </UpdateParameters>
      </asp:SqlDataSource>
  
      </asp:Panel>
               <asp:Panel runat="server" ID="panel2">
               <asp:GridView ID="GridView2"  CssClass= "table table-striped table-bordered table-condensed" runat="server" DataKeyNames="MatchName" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource2">
                   <Columns>
                       <asp:BoundField DataField="MatchName" HeaderText="MatchName" SortExpression="MatchName" />
                       <asp:BoundField DataField="VenueName" HeaderText="VenueName" SortExpression="VenueName" />
                       <asp:BoundField DataField="ScheduleDate" HeaderText="ScheduleDate" SortExpression="ScheduleDate" />
                       <asp:BoundField DataField="StartTime" HeaderText="StartTime" SortExpression="StartTime" />
                       <asp:BoundField DataField="EndTime" HeaderText="EndTime" SortExpression="EndTime" />
                   </Columns>
                   </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" DeleteCommand="delete  FROM IPL_MGMT_SYSTEM.Schedule where [MatchName]=@MatchName" SelectCommand="SELECT  MatchName, VenueName,ScheduleDate, StartTime, EndTime  FROM IPL_MGMT_SYSTEM.Schedule where [MatchName]=@MatchName
" UpdateCommand="update IPL_MGMT_SYSTEM.Schedule set [MatchName]=@MatchName, [VenueName]=@VenueName, [ScheduleDate]=@ScheduleDate,[StartTime]=@StartTime,[EndTime]=@EndTime where [MatchName]=@MatchName">
                       <DeleteParameters>
                           <asp:Parameter Name="MatchName" />
                       </DeleteParameters>
                       <SelectParameters>
                           <asp:ControlParameter ControlID="searchtxt1" Name="MatchName" PropertyName="Text" />
                       </SelectParameters>
                       <UpdateParameters>
                           <asp:Parameter Name="MatchName" />
                           <asp:Parameter Name="VenueName" />
                           <asp:Parameter Name="ScheduleDate" />
                           <asp:Parameter Name="StartTime" />
                           <asp:Parameter Name="EndTime" />
                       </UpdateParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
           </div>
    </div>
    </div>   

            </center>
</asp:Content>
