<%@ Page Title="" Language="C#" MasterPageFile="~/Employee_Master.Master" AutoEventWireup="true" CodeBehind="CategoryDetails.aspx.cs" Inherits="Presentation_Layer.Account.Employee.Emp_TicketCategory.CategoryDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     <br />
    <br />
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
    </p>

   
        <center>
   <div style="height:100%;" class="panel panel-default" >
       <div class="panel panel-info">
       <div class="panel-heading"> <h3>Ticket Category Info</h3></div></div>
   
    
       <div class="panel-body" >
       
           <div>
              
               <asp:Label Text="Search:" style="text-align:right" runat="server"></asp:Label>
               <asp:TextBox style="text-align:left" OnTextChanged="searchtxt1_TextChanged" runat="server" ID="searchtxt1" AutoPostBack="true" ></asp:TextBox><i class="fa fa-search"></i>
                 <button style="text-align:left" onclick="btnrefresh" class="btn btn-primary"><span class="glyphicon glyphicon-refresh"></span> Refresh</button>
           </div>
           <br /><br />
           <div style="width: 50%; height: 290px;" >
              <a href="~/Account/Employee/Emp_TicketCategory/Add_TicketCategpry" runat="server">Add Ticket Category</a>
  <asp:Panel runat="server" ID="panel1">
       
   <asp:GridView ID="GridView1"  CssClass= "table table-striped table-bordered table-condensed" runat="server" AllowPaging="True" DataKeyNames="TicketCategoryName" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1">

       <Columns>
           <asp:BoundField DataField="TicketCategoryName" HeaderText="TicketCategoryName" SortExpression="TicketCategoryName" />
           <asp:BoundField DataField="TicketDescription" HeaderText="TicketDescription" SortExpression="TicketDescription" />
       </Columns>

   </asp:GridView>
      <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" UpdateCommand="update IPL_MGMT_SYSTEM.TicketCategory set [TicketCategoryName]=@TicketCategoryName, [TicketDescription]=@TicketDescription where [TicketCategoryName]=@TicketCategoryName" DeleteCommand="delete FROM IPL_MGMT_SYSTEM.TicketCategory where [TicketCategoryName]=@TicketCategoryName" SelectCommand="SELECT TicketCategoryName, TicketDescription FROM IPL_MGMT_SYSTEM.TicketCategory"></asp:SqlDataSource>
      </asp:Panel>
               <asp:Panel runat="server" ID="panel2">
               <asp:GridView ID="GridView2"  CssClass= "table table-striped table-bordered table-condensed" runat="server" DataKeyNames="TicketCategoryName" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource2">

                   <Columns>
                       <asp:BoundField DataField="TicketCategoryName" HeaderText="TicketCategoryName" SortExpression="TicketCategoryName" />
                       <asp:BoundField DataField="TicketDescription" HeaderText="TicketDescription" SortExpression="TicketDescription" />
                   </Columns>

               </asp:GridView>
                   <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:16MayCHNConnectionString %>" DeleteCommand="delete TicketCategoryName, TicketDescription FROM IPL_MGMT_SYSTEM.TicketCategory" SelectCommand="SELECT TicketCategoryName,TicketDescription FROM IPL_MGMT_SYSTEM.TicketCategory where [TicketCategoryName]=@TicketCategoryName">
                       <SelectParameters>
                           <asp:ControlParameter ControlID="searchtxt1" Name="TicketCategoryName" PropertyName="Text" />
                       </SelectParameters>
                   </asp:SqlDataSource>
               </asp:Panel>
           </div>
    </div>
    </div>   

            </center>
</asp:Content>
